//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Karate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo_Details
    {
        public int Id { get; set; }
        public string UniqueName { get; set; }
        public string ModuleName { get; set; }
        public string FolderName { get; set; }
        public string FolderPath { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Comments { get; set; }
        public string OptionOne { get; set; }
    }
}
