//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KarateJanNine
{
    using System;
    using System.Collections.Generic;

    public partial class Customer
    {
        public Customer()
        {
            this.CashTransactions = new HashSet<CashTransaction>();
            this.CommissionTransactions = new HashSet<CommissionTransaction>();
            this.Recharges = new HashSet<Recharge>();
            this.WalletTransactions = new HashSet<WalletTransaction>();
        }
    
        public int CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string ContactNumber { get; set; }
        public string EmailAddress { get; set; }
        public string ContactAddress { get; set; }
        public string CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
    
        public virtual ICollection<CashTransaction> CashTransactions { get; set; }
        public virtual ICollection<CommissionTransaction> CommissionTransactions { get; set; }
        public virtual ICollection<Recharge> Recharges { get; set; }
        public virtual ICollection<WalletTransaction> WalletTransactions { get; set; }
    }
}
