//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KarateJanNine
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recharge
    {
        public int RechargeID { get; set; }
        public string Message { get; set; }
        public string isError { get; set; }
        public string TimeStamp { get; set; }
        public string Partnerid { get; set; }
        public string RechargeTo { get; set; }
        public string OperatorName { get; set; }
        public string Amount { get; set; }
        public string ProviderId { get; set; }
        public string Profit { get; set; }
        public string OperatorReference { get; set; }
        public string Status { get; set; }
        public string Statement { get; set; }
        public string PaymentId { get; set; }
        public string CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
    }
}
