//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KarateJanNine
{
    using System;
    using System.Collections.Generic;
    
    public partial class WalletTransaction
    {
        public int WalletTransactionID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<bool> IsCredit { get; set; }
        public string WalletTransactionDate { get; set; }
        public string WalletTransactionReferenceDescription { get; set; }
        public string WalletTransactionReferenceID { get; set; }
        public string WalletTransactionAmount { get; set; }
        public string WalletTransactionDescription { get; set; }
        public string WalletBalance { get; set; }
        public string CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
