//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KarateJanNine
{
    using System;
    using System.Collections.Generic;
    
    public partial class WalletTransaction
    {
        public int WalletTransactionID { get; set; }
        public int TransactionTypeID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string Date { get; set; }
        public string Reference { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsRecharge { get; set; }
        public string WalletTransactionAmount { get; set; }
        public string WalletBalance { get; set; }
        public string RechargeAmount { get; set; }
        public string ComissionAmount { get; set; }
        public string CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ComissionTotal { get; set; }
        public Nullable<bool> IsProfitTransfer { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
